### ISSUE TITLE
Problems fitting M4 model

### ISSUE THREAD

**Issue by CakaKarlsson** [joshcullen/bayesmove#8]
Hey. 
Thank you for a good video and material. 
I'm trying to fit the M4 model, by following your script from the animal movement workshop.
Although, I got the following error when trying to fit the model, which I can´t solve:

Error in (function (.x, .y, .f, ..., .progress = FALSE)  : ℹ In index: 1.
ℹ With name: 193208.
Caused by error in `-id`:
! invalid argument to unary operator

Thank you 
Kindly 
Caka

**Comment by joshcullen** [comment]
Hi Caka,

It's difficult to diagnose exactly what's going on based on the error message alone. I re-ran the code provided in the M4 vignettes on the bayesmove package website (joshcullen.gituhb.io/bayesmove), but didn't receive an error like this.

Based on some previous datasets I've analyzed with this model, I've had issues come up before when the "id" column is numeric, presumably because of how at least one of the functions operates for applying the function to each ID separately and then joining together again. So my recommendation is to try converting the 'id' column to class 'character' instead and then try again.

If you still are receiving this (or another) error, please provide more info about which function produces this error and ideally a reproducible example that I can troubleshoot.

Best,
  Josh

**Comment by CakaKarlsson** [comment]
Thank you so much Josh for your reply.
I've implemented your suggestions.
I have changed the id column to include the individual names, I also changed the id number column into a character but the same problem rose for both possible solutions. The problems arise when I tried to run the model i.e:
dat.res.seg1<- segment_behavior(data = dat.list.sub, ngibbs = ngibbs, nbins = nbins,
                                alpha = alpha)

I ran the following script until I faced the issue:

library(tidyverse)
library(lubridate)
library(bayesmove)  #v0.2.1
library(sf)  #v1.0.7
library(rnaturalearth)
library(plotly)
library(furrr)
library(future)

#### Load data ####

dat <- read.csv("Night_All.csv")

glimpse(dat)
summary(dat)
names(dat)

#### Wrangle data for analysis using {bayesmove} ####

# Convert all 'date' to datetime format
# OBS: I Can use timestep even if it contains time because he (josh) did it). 
#SO I don´t need to use the column date
dat <- dat %>%
  mutate(date = as_datetime(timestamp, tz="Africa/Lagos", format="%Y-%m-%d %H:%M"))
#OBS: weird but there is a new column now called date and the format is correct

#OBS: change id to tag.local.identifier 
dat2<- prep_data(dat = dat, coord.names = c("location.long","location.lat"), id = "tag.local.identifier")
head(dat2)

#OBS: since x and y are in meters

# Let's double-check that all time-steps are at 8 hrs (28800 s)
#OBS; For me it differs a lot
table(dat2$dt)  
dat$tag.local.identifier<- as.character(dat$tag.local.identifier)
str(dat)

# Since we don't need to filter out obs at other time intervals, we still need to add required variables to data.frame
dat2 <- dat2 %>%
  group_by(tag.local.identifier) %>%  #need to number rows separately for each ID
  mutate(time1 = 1:n(),
         obs = 1:n()) %>%
  ungroup()

#verify that it worked properly
dat2 %>%
  dplyr::select(tag.local.identifier, timestamp, time1, obs) %>%   #select only a few cols since tibble hides time1 and obs
  split(.$tag.local.identifier) %>%
  head()


# For direct comparison w/ HMM results, create displacement variable
dat2$disp <- sqrt(dat2$NSD)



#### Discretize data streams for models ####
#Discretization is the process through which we can transform continuous variables,
#models or functions into a discrete form

# Viz density plots of each data stream
ggplot(dat2) +
  geom_density(aes(step), fill = "cadetblue") +
  theme_bw()

#Turning angles
ggplot(dat2) +
  geom_density(aes(angle), fill = "firebrick") +
  theme_bw()

#OBS: Displacement variable= The variable we created from NSD. So meters
#from first loc. I changed it to NSD tho
ggplot(dat2) +
  geom_density(aes(NSD), fill = "goldenrod") +
  theme_bw()



# Define bin limits (and number of bins)

# turning angle (naturally constrained in [0,2*pi] or [-pi,+pi])
angle.bin.lims <- seq(from = -pi, to = pi, by = pi/4)  #8 bins
#OBS: I used the same 8 bins cuz he recommended that 8 bins does a good 
#job in general.

# step length (must be positive, but no upper bound)
step.bin.lims <- c(seq(from = 0, to = 1, length = 5), max(dat2$step, na.rm = TRUE))  
#I set it to be 10 steps between 0-1 and after 1 it´s one step

# displacement (must be positive, but no upper bound)
NSD.bin.lims <- seq(from = 0, to = 60, by = 10)  
#is gonna be


angle.bin.lims
step.bin.lims
NSD.bin.lims


# Discretize data streams
dat.disc <- discrete_move_var(dat2,
                              lims = list(step.bin.lims, angle.bin.lims, NSD.bin.lims),
                              varIn = c("step","angle","NSD"),
                              varOut = c("SL","TA","NSD"))



# Viz histograms of discretized data streams
ggplot(dat.disc) +
  geom_bar(aes(SL), fill = "cadetblue") +
  theme_bw()

ggplot(dat.disc) +
  geom_bar(aes(TA), fill = "firebrick") +
  theme_bw()

ggplot(dat.disc) +
  geom_bar(aes(NSD), fill = "goldenrod") +
  theme_bw()


#### Fit segment-level mixed-membership model to estimate states ####

# Convert data to list by ID
dat.list <- dat.disc %>%
  df_to_list(., "tag.local.identifier")

# Only retain id and discretized data streams
dat.list.sub<- map(dat.list,
                   subset,
                   select = c(tag.local.identifier, SL, TA, NSD))



# Run the segmentation model (unsupervised)
set.seed(123)

alpha<- 1  # hyperparameter for prior (Dirichlet) distribution
ngibbs<- 1000  # number of iterations for Gibbs sampler
nbins<- c(5,8,6)  # define number of bins per data stream (in order from dat.list.sub)

progressr::handlers(progressr::handler_progress(clear = FALSE))  #to initialize progress bar
future::plan(multisession, workers = availableCores() - 2)  #run MCMC chains in parallel

dat.res.seg1<- segment_behavior(data = dat.list.sub, ngibbs = ngibbs, nbins = nbins,
                                alpha = alpha)

I can send you my dataset if you would like to run through it.
Thank you very much
Kindly
Caka
________________________________

**Comment by joshcullen** [comment]
Hi Caka,

It seems like there might be a couple spots in your code where errors may have been introduced (e.g., not filtering out irregular time steps), but difficult to say what is directly causing the error.

So yes, if you're able to email me some of your data then I can take a look at it and try to figure out why it's not working. You can send the file to joshcullen10@gmail.com.

Best,
  Josh

**Comment by joshcullen** [comment]
Hi Caka,

I ran the code with your data while filtering out irregular observations and think issue is likely related to the ID column not being labeled as "id" for the model to run properly. I've included a more detailed description and a modified R script in my email reply, but I will close out this issue as completed as long as it works on your end.

Best,
Josh
